services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  migrator:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./user-service/migrations:/migrations
    command: [
      "-path=/migrations",
      "-database=postgres://user:password@postgres:5432/user_service?sslmode=disable",
      "up"
    ]
    restart: on-failure

  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./user-service/.env
    depends_on:
      - postgres
      - minio
      - migrator
    ports:
      - "8082:8082"
      - "50051:50051"
    volumes:
      - ./user-service/.env:/app/.env
    restart: unless-stopped

volumes:
  pgdata:
  minio-data:
